{
 "title": "ExampleCo Machine Data",
 "time": { "from": "2018-10-02T13:15:22.174Z", "to": "2019-05-14T11:53:51.608Z" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "Machine",
    "query": "select machine_name from machine_metrics group by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Metric 1 - Max, Avg, Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  machine_name AS metric,\n  max(metric_1) AS \"max\",\n  avg(metric_1) AS \"avg\",\n  min(metric_1) AS \"min\"\nFROM machine_metrics\nWHERE\n  machine_name in ([[machine]])\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Metric 2 - Max, Avg, Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  machine_name AS metric,\n  max(metric_2) AS \"max\",\n  avg(metric_2) AS \"avg\",\n  min(metric_2) AS \"min\"\nFROM machine_metrics\nWHERE\n  machine_name in ([[machine]])\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Metric 3 - Max, Avg, Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  machine_name AS metric,\n  max(metric_3) AS \"max\",\n  avg(metric_3) AS \"avg\",\n  min(metric_3) AS \"min\"\nFROM machine_metrics\nWHERE\n  machine_name in ([[machine]])\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Metric 3 - Max, Avg, Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  machine_name AS metric,\n  max(metric_4) AS \"max\",\n  avg(metric_4) AS \"avg\",\n  min(metric_4) AS \"min\"\nFROM machine_metrics\nWHERE\n  machine_name in ([[machine]])\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}